[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
    m5stack/M5Cardputer@^1.0.2
monitor_speed = 115200
upload_port = /dev/cu.usbmodem3101
monitor_port = /dev/cu.usbmodem3101
