[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
    m5stack/M5Cardputer@^1.0.2
build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"
    -DCLAUDE_SERVER=\"${sysenv.CLAUDE_SERVER}\"
monitor_speed = 115200
; Uncomment and set your device port if auto-detection fails:
; upload_port = /dev/cu.usbmodem3101
; monitor_port = /dev/cu.usbmodem3101
